---
- name: Set facts
  set_fact:
    key: "{{ email | password_hash('sha256') }}"
    expiry: "{{ lookup('pipe','date +%s -d +1hour') }}"

- name: Template a file
  template:
    src: email_template.j2
    dest: "/tmp/email_{{ expiry }}.txt"

- name: Sending an automated e-mail to user
  mail:
    subtype: html
    host: smtp.corp***REMOVED***com
    port: 25
    from: no-reply@***REMOVED***com
    to: "{{ email }}"
    subject: "***REMOVED***: Activate your account"
    body: "{{ lookup('file', '/tmp/email_' + expiry + '.txt') }}"

- name: Create entry at spreadsheet
  uri:
    url: "https://script.google.com/macros/s/***REMOVED***/exec?op=add&key={{key}}&expiry={{expiry}}"

- name: TESTING Poll until account activated or 1hour
  shell: curl -k -L "https://script.google.com/macros/s/***REMOVED***/exec?op=query&key={{key}}"
  register: result_test

- debug:
    var: result_test

- name: Poll until account activated or 1hour
  shell: curl -k -L "https://script.google.com/macros/s/***REMOVED***/exec?op=query&key={{key}}"
  register: result
  until: "{{ '<result>E</result>' in result.stdout or '<result>A</result>' in result.stdout }}"
  retries: 360
  delay: 10
