---
- name: Set facts
  set_fact:
    key: "{{ 59 |random(seed=email) }}"
    expiry: "{{ lookup('pipe','date +%s -d '+1 hour'') }}"

- name: Template a file
  template:
    src: email_template.j2
    dest: /tmp/email_body.txt

- name: Sending an automated e-mail to user
  mail:
    subtype: html
    host: smtp.corp***REMOVED***com
    port: 25
    from: no-reply@***REMOVED***com
    to: "{{ email }}"
    subject: "***REMOVED***: Activate your account"
    body: "{{lookup('file', '/tmp/email_body.txt')}}"

- name: Create entry at spreadsheet
  uri:
    url: "https://script.google.com/macros/s/***REMOVED***/exec?op=add&key={{key}}&expiry={{expiry}}"
